### ISSUE TITLE
Handle overridden properties in JSON serialization

### ISSUE THREAD

**Issue by loradd** [Strumenta/kolasu#87] opened 2022-07-13 13:07 UTC
At the moment, JSON serialization does not handle duplicate properties resulting from overriding in data class definitions and throws an error. 

In the following data class definition, there will be two different properties, i.e. `Node.specifiedPosition` and `specifiedPosition`, that should really be considered as one. 

```
data class ExampleNode(
    override var specifiedPosition: Position? = null
) : Node(specifiedPosition)
```

Whenever duplicate properties are found, the JSON serializer should check whether these might be related, e.g. one overriding the other. If so, only one of these should be taken into consideration. Otherwise, an error should be thrown as with ordinary duplicate properties.

**Comment by ftomassetti** [comment] 2022-07-27 14:48
I am unable to reproduce this exact case as specifiedPosition was removed. I added some tests in #92 
@loradd can you think of other ways to reproduce it?

**Comment by ftomassetti** [comment] 2022-07-28 06:23
Thank you for the feedback. I will then merge #92 and close this one.

**Closed by ftomassetti** 2022-07-28 06:23 UTC
Labels: bug
